name: flutter_exprtk_native
description: Windows implementation of the flutter_exprtk plugin.
repository: https://github.com/DominikStarke/flutter_exprtk/
version: 0.0.8

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_exprtk_platform_interface: ^0.0.8
  flutter_exprtk_platform_interface:
    path: ../flutter_exprtk_platform_interface
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_exprtk
    platforms:
      android:
        ffiPlugin: true
        fileName: flutter_exprtk_native.dart
        package: com.dost.flutter_exprtk_native
      ios:
        ffiPlugin: true
        fileName: flutter_exprtk_native.dart
      macos:
        ffiPlugin: true
        fileName: flutter_exprtk_native.dart
      windows:
        ffiPlugin: true
        fileName: flutter_exprtk_native.dart
      linux:
        ffiPlugin: true
        fileName: flutter_exprtk_native.dart