name: NAME_android
description: Android implementation of the NAME plugin.
repository: GITHUB/tree/master/NAME_android
version: VERSION

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  NAME_platform_interface: #^VERSION
    path: ../NAME_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: NAME
    platforms:
      android:
        package: BUNDLE.NAME_android
        pluginClass: CLASSAndroidPlugin