name: flutter_exprtk
description: flutter_exprtk is a FFI wrapper for the exptrk Mathematical Expressions Toolkit Library
repository: https://github.com/DominikStarke/flutter_exprtk/
version: 0.0.7

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO: Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  flutter_exprtk_platform_interface: ^0.0.7
    #path: ../flutter_exprtk_platform_interface
  flutter_exprtk_native: ^0.0.7
    #path: ../flutter_exprtk_native
  flutter_exprtk_web: ^0.0.7
    #path: ../flutter_exprtk_web


flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_exprtk_native
      ios:
        default_package: flutter_exprtk_native
      windows:
        default_package: flutter_exprtk_native
      web:
        default_package: flutter_exprtk_web