name: flutter_exprtk_android
description: Android implementation of the flutter_exprtk plugin.
repository: git@github.com:DominikStarke/flutter_exprtk.git/tree/master/flutter_exprtk_android
version: 0.0.7

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_exprtk_platform_interface: #^0.0.7
    path: ../flutter_exprtk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_exprtk
    platforms:
      android:
        package: com.dost.flutter_exprtk_android
        pluginClass: FlutterExprtkAndroidPlugin