name: NAME
description: Add description
repository: GITHUB/tree/master/NAME
version: VERSION

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO: Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  NAME_platform_interface: ^VERSION
  NAME_android: ^VERSION
  NAME_ios: ^VERSION
  NAME_windows: ^VERSION
  NAME_web: ^VERSION

flutter:
  plugin:
    platforms:
      android:
        default_package: NAME_android
      ios:
        default_package: NAME_ios
      windows:
        default_package: NAME_windows
      web:
        default_package: NAME_web